import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

// The live WordPress site serves every URL with a trailing slash and no `www`
// stripping, e.g. https://www.explorebowland.co.uk/caton-moor/
// We MUST preserve these exactly, so:
//   - trailingSlash: 'always'  -> keep the trailing slash
//   - build.format: 'directory' -> emit /caton-moor/index.html
// Redirects for legacy variants (attachment pages, /home/ prefixes, etc.) are
// generated by the importer into src/pages and public/_redirects.
export default defineConfig({
  site: 'https://www.explorebowland.co.uk',
  trailingSlash: 'always',
  build: { format: 'directory' },
  integrations: [sitemap()],
  image: {
    // Allow Astro <Image> to optimise remote images served from the R2 CDN.
    // Update the hostname once the R2 custom domain is live.
    remotePatterns: [{ protocol: 'https' }],
  },
});
